config/routes.rb
Rails.application.routes.draw do
  root "articles#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :articles do
    resources :comments
    member do
      patch :report 
    end
  end

  devise_for :users
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible
  before_save :check_reports_count

  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
  validates :user, presence: true
  has_one_attached :image

  private

  def check_reports_count
    if reports_count >= 3
      self.status = 'archived'
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  belongs_to :article
  belongs_to :user

  validates :user, presence: true
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  def archived?
    status == 'archived'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_article, only: [:show, :edit, :update, :destroy, :report]
  before_action :authorize_user!, only: [:edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
    if @article.status == 'public' || @article.user == current_user
      render :show
    else
      redirect_to articles_path, alert: "You are not authorized to view this article"
    end
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.image.attach(params[:image])
    @article.save 

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      @article.image.attach(params[:image]).save if params[:image].present?
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    redirect_to root_path, status: :see_other
  end

  def report
    @article.reports_count = @article.reports_count + 1
    if @article.save
      redirect_to @article, notice: 'Article has been reported.'
    else
      redirect_to @article, alert: 'Article could not be reported.'
    end
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :status, :image).merge(user: current_user)
    end

    def set_article
      @article = Article.find(params[:id])
    end

    def authorize_user!
      redirect_to articles_path, alert: "You are not authorized to do this article" unless @article.user == current_user
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :status %><br>
    <%= form.select :status, Visible::VALID_STATUSES, selected: article.status || 'public' %>
  </div>

  <div>
    <%= form.label :image %><br>
    <%= form.file_field :image %>
    <% article.errors.full_messages_for(:image).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<% if user_signed_in? %> 
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
  <h1>Articles</h1>

  <ul>
    <% @articles.each do |article| %>
      <% unless article.archived? %>
        <li>
          <%= link_to article.title, article %>
        </li>
      <% end %>
    <% end %>
  </ul>

  <%= link_to "New Article", new_article_path %>
<% else %>
  <%= button_to "Sign in", new_user_session_path %> 
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<% if @article.image.attached? %>
  <%= image_tag @article.image %>
<% end %>

<p><%= @article.body %></p>
<ul>
<% if( @article.user == current_user) %>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= link_to "Destroy", article_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
<% end %>
  <li><%= link_to "Report", report_article_path(@article), data: {turbo_method: :patch} %></li>
</ul>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form'  %>

app/views/comments/_comment.html.erb
<% @article.comments.each do |comment| %>
  <% unless comment.archived? %>
    <p>
      <strong>Commenter:</strong>
      <%= comment.commenter %>
    </p>
    <p>
      <strong>Comment:</strong>
      <%= comment.body %>
    </p>
    <p>
    <%= link_to "Destroy Comment", [comment.article, comment], data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>
  </p>
  <% end %>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.label :status %><br>
    <%= form.select :status, Visible::VALID_STATUSES, selected: 'public' %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p> 
    <p class="alert"><%= alert %></p> 
    <%= yield %>
  </body>
</html>